### ISSUE TITLE
Rate is greater than one for the primary education rate scatter plot

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/obesity-explorer-R#25]

**Comment by tanmaysharma19** [comment]
- We've decided to discard primary education rate as a regressor in our association plot since calculation for this metric requires having data about age and population numbers for children who are of graduation age at an annual level. 
- We'll instead be using `Literacy Rate` as an indicator ( See #59)

**Comment by rtaph** [comment]
Closed via #66
