### ISSUE TITLE
Make the tabs thinner

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/obesity-explorer-R#35]

**Comment by jraza19** [comment]
In trying to resolve this, the team discovered that this is more difficult than anticipated as the height parameters for the dcc tabs is insufficient. This is because the selected tab height is a different attribute and would likely require a global css file to be read in at the head of the app. Since this is a different programming paradigm from the pass-by-parameter approach, and because the tabs do not look bad,  the team decided to forego this feature request.
